// Pure helper functions for the create-checkout-session Edge Function.
// Zero external imports — safe to unit-test in Node.js without a Deno environment.

// UUID v4 regex. Validates that the string looks like a standard v4 UUID before
// using it as a key or writing it to the database.
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

/**
 * Returns true when str is a valid UUID v4 string (case-insensitive).
 * Used to validate user-supplied IDs before they touch the database or Stripe.
 *
 * @param {unknown} str
 * @returns {boolean}
 */
export function isValidUUID(str) {
  return typeof str === 'string' && UUID_RE.test(str)
}

/**
 * Builds the Stripe idempotency key for a checkout session creation request.
 *
 * Key design:
 *   - Scoped to one user (userId) and one checkout attempt (attemptId).
 *   - The frontend generates a fresh UUID per click, so different checkout
 *     attempts always produce different keys (no accidental reuse of an old
 *     Stripe session). A network retry of the same request sends the same
 *     attemptId, which Stripe deduplicates correctly.
 *   - A permanent key (e.g. userId+priceId) would incorrectly reuse a
 *     completed or expired session from a prior payment attempt.
 *
 * Precondition: both userId and attemptId must be valid UUIDs (callers must
 * validate before calling this function).
 *
 * @param {string} userId   — Supabase user ID (verified from auth token)
 * @param {string} attemptId — Per-click UUID generated by the frontend
 * @returns {string}
 */
export function buildIdempotencyKey(userId, attemptId) {
  return `checkout-${userId}-${attemptId}`
}

/**
 * Returns true when the subscription status means the user already has an
 * active or dunning subscription (should not be offered a new checkout).
 *
 * Statuses that block a new checkout:
 *   - 'active'   — subscription is current and paid
 *   - 'past_due' — payment failed, Stripe retrying; access preserved during
 *                  dunning window, and a new checkout would create a duplicate
 *
 * All other statuses (canceled, incomplete, incomplete_expired, unpaid,
 * trialing, paused, none) allow starting a new checkout.
 *
 * @param {string|null|undefined} status
 * @returns {boolean}
 */
export function isBlockedByExistingSubscription(status) {
  return status === 'active' || status === 'past_due'
}
